name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - database

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build backend image
        working-directory: ./backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/quirknotes_backend:latest -f Dockerfile_backend .

      - name: Push backend image to Docker Hub
        working-directory: ./backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/quirknotes_backend:latest
